### ISSUE TITLE
Unreal Freeze over Serial

### ISSUE THREAD

**Issue by JoelWachsler** [microsoft/AirSim#1055]
Hi,

I'm trying to send and receive MAVLink messages over serial to and from AirSim using an STM32F4 discovery board  via an USB to serial adapter but whenever I'm starting the simulation Unreal freezes. It seems like this is only happening when I try to connect to one of my USB to serial converters (tried two different ones with and without the board connected).
I've debugged AirSim by adding breakpoints in the `processMavMessages` method in `MavLinkDroneController.hpp` and it seems like it's getting my Heartbeat messages and I'm also receiving HIL_GPS and HIL_SENSOR messages on the board so I don't think there's any problem with the communication.

It seems like AirSim is waiting for something because almost no CPU or GPU processing is used which can be seen in the following image:
![img](https://user-images.githubusercontent.com/8604164/39620562-e5b4f99c-4f8b-11e8-91d4-772505d41e68.png)

The freeze looks like this in Unreal:
![image](https://user-images.githubusercontent.com/8604164/39620774-8f50082a-4f8c-11e8-980a-d1ddfacf0a4c.png)

### Versions:
Unreal Engine: 4.18.3
AirSim: 297f1c49d3ef0a1a0f0d841ef7dafa89603db327
Visual Studio: 15.6.7

### Settings:
```json
{
  "SettingsVersion": 1.0,
  "DefaultVehicleConfig": "PX4",
  "PX4": {
      "UseSerial": true,
      "SerialBaudRate": 115200,
      "SerialPort": "COM5"
  }
}
```

### System specs:

![image](https://user-images.githubusercontent.com/8604164/39619891-a4647d2a-4f89-11e8-9343-c8b4ef9a64bb.png)
![image](https://user-images.githubusercontent.com/8604164/39619896-b0797e80-4f89-11e8-95be-6f934cf9541b.png)
![image](https://user-images.githubusercontent.com/8604164/39619897-b31902dc-4f89-11e8-8efd-939f9931bdf9.png)
![image](https://user-images.githubusercontent.com/8604164/39619901-b641e032-4f89-11e8-9e2a-3e634f145c49.png)
![img](https://user-images.githubusercontent.com/8604164/39620133-72069754-4f8a-11e8-970e-ef70d8a803b0.png)

**Comment by Pierrolo** [comment]
I don't know if this will fix it for you, but I've read (don't emember where) that AirSim is mainly compatible with UE 4.16, maybe try to download the editor version 4.16 and try with that, it should fix it I believe

**Comment by JoelWachsler** [comment]
> I don't know if this will fix it for you, but I've read (don't emember where) that AirSim is mainly compatible with UE 4.16, maybe try to download the editor version 4.16 and try with that, it should fix it I believe

I tried with Unreal Version 4.16 yesterday and that's when I discovered this problem and upgraded AirSim to the latest commit and Unreal to 4.18 in hopes of it being resolved.

**Comment by JoelWachsler** [comment]
I finally got it working by proxying the connection with MavLinkTest instead of connecting directly to AirSim but the original problem still persists.

I think this problem has something to do with the `physics_world_` locking because Unreal doesn't freeze when the locking mechanism is removed from the [ASimModeWorldBase::Tick](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/SimMode/SimModeWorldBase.cpp#).

I've also discovered that Unreal only freezes whenever I'm trying to connect with a physical COM port and not a virtual one.

Here are also two CPU profiles if they're of any use.

### CPU profiling when connecting over serial (Unreal Freeze):
![image](https://user-images.githubusercontent.com/8604164/39666300-a4849a7e-50a1-11e8-9eeb-eefa18059e1e.png)

### CPU profiling when connecting over UDP (Works fine):
![image](https://user-images.githubusercontent.com/8604164/39666295-8dbae168-50a1-11e8-9bcb-78f491ed5446.png)

**Comment by sytelus** [comment]
We are currently not working on PX4 however you can help us improve this. Please feel free to contribute docs or code update!

**Comment by VikingDai** [comment]
I find the problem ,"SerialBaudRate": 115200,   change the buardrate to 912600 or larger ,this may fixed.

**Comment by VikingDai** [comment]
another way ,you may change the sensor's send speed.

**Comment by clovett** [comment]
I'm curious if you still have this problem using latest AirSim bits.

**Comment by jonyMarino** [comment]
closed due to inactivity. doc update pending
