### ISSUE TITLE
Linux binary crashing with PX4 SITL

### ISSUE THREAD

**Issue by pgashwin** [Microsoft/AirSim#1388]
Trying to run the Linux Binary with PX4 SITL setup and it crashes before starting. It works fine without the SITL setup though. 
Here'e the error log. 
![linuxerror](https://user-images.githubusercontent.com/17004686/45341435-47eb1a00-b5b8-11e8-9262-6734d2803d9f.png)

**Comment by petergerten** [comment]
Related issue https://github.com/Microsoft/AirSim/issues/1516

**Comment by madratman** [comment]
@clovett do you think this is fixed with the latest changes?

**Comment by fennel-labs** [comment]
@sytelus:
This error is not yet fixed.
Tested with Airsim@67f438629c4ca4bcf25436d5e21e9839487a6491 and PX4 1.8.2 Release on Ubuntu 16.04.
