### ISSUE TITLE
Accelerator jumps periodically in z-axis

### ISSUE THREAD

**Issue by mocibb** [Microsoft/AirSim#437]
Hi, i am trying use the latest Airsim and PIX4 firmware(v1.6.5) for HIL simulation.
When uav is on ground, in qgroundcontrol i found accelerator zacc  value jump between 0 and -10.
that cause estimator of PIX4 getting crazy.
I am unable to figure out why this happened, have any ideas about this

![z-acc-jump](https://user-images.githubusercontent.com/18642/29697080-9ab5fd1a-897f-11e7-896a-7246202c4f47.PNG)

**Comment by sytelus** [comment]
I think this was solved using ground lock before. I'll have to re-test and get back to you.

**Comment by mocibb** [comment]
I used latest commit(a20728d) for testing.
it seems z-acc still have some problems, but different from previous one.
![z-acc-jump_2](https://user-images.githubusercontent.com/18642/29870420-f2a76f66-8db9-11e7-9b5e-d0770547fafc.PNG)

I also found altitude have been periodically reset.
![alt_wrong](https://user-images.githubusercontent.com/18642/29870448-165a6f9e-8dba-11e7-9f2e-5266faba3f6a.PNG)

**Comment by lovettchris** [comment]
This might be fixed now with [my new pull request](https://github.com/Microsoft/AirSim/pull/670).

**Comment by lovettchris** [comment]
Please reopen if you still see this, thanks.
