### ISSUE TITLE
AirSim_FrSkyTaranis.bin fails to be installed on FrSky Taranis X9D Plus

### ISSUE THREAD

**Issue by PanGroup** [Microsoft/AirSim#486]
Following Note on FrSky Taranis X9D Plus:
"FrSky Taranis X9D Plus is real UAV remote control with an advantage that it has USB port so it can be directly connected to PC. You can download AirSim config file and follow this tutorial to import it in your RC. You should then see "sim" model in RC with all channels configured properly."

I have downloaded the AirSim config file from https://github.com/Microsoft/AirSim/blob/master/docs/misc/AirSim_FrSkyTaranis.bin, which is then copied to the models folder in the X9D Plus sd card. However, when I am trying to restore "airsim_frskytaranis" model following the tutorial to import it in the RC, it fails  with an error "Incompatible". I have updated the firmware to the latest version, but this error still remains.

**Comment by PanGroup** [comment]
The problem has been solved. AirSim_FrSkyTaranis.bin file downloaded from https://github.com/Microsoft/AirSim/blob/master/docs/misc/AirSim_FrSkyTaranis.bin via webpage is not exactly the one for Taranis X9D Plus. The correct file should be downloaded via github client.

**Comment by sytelus** [comment]
I'm assuming you had download trouble from GitHub? I think downloading "raw" data should work.

**Comment by AloshkaD** [comment]
@PanGroup I've downloaded it from github and still getting incompatible. What opentx version do you have?

**Comment by AloshkaD** [comment]
I've created a new config file

**Comment by Ahmad-Drak** [comment]
@AloshkaD not working on my end. did your bin file work?

**Comment by zardosht** [comment]
@AloshkaD Can you please share your config file?
