### ISSUE TITLE
Depth map got messed up under some circumstances

### ISSUE THREAD

**Issue by kaihuchen** [Microsoft/AirSim#500]
I am seeing incorrect reported depth information under some circumstances. This applies to both the DepthMeters mode as well as the new DepthPerspective mode. Below I will describe it using information collected with the older DepthMeters mode.

I have an autonomous car that navigates strictly based on depth information. In the beginning of a testing session the depth information always  looks fine. The car is also able to navigate around other parked cars on the street using the depth information without problem. However, whenever the car reaches the end of a T intersection and begins to backup, then the depth map got largely blanked out with uniformly incorrect distance information (i.e., see the GIF below, look for the large red area in the depth map as the car is backing up).

![x2](https://user-images.githubusercontent.com/13685803/31048666-067ebb36-a5f0-11e7-8d10-5410a93f9655.gif)

The above is perfectly reproducible. I have also seen this occur when the car goes off road (say, going into backyards).

**Comment by Kjell-K** [comment]
Please refer to issue #491 and #478. There is a change in the master branch now with using DepthPlanner instead of DepthMeters. I have not tried it yet, but it is supposed to solve this issue as well.

**Comment by kaihuchen** [comment]
FYI, my test above was already using the latest master branch from this morning.
There are some problems with DepthPlanner, where I got a strangely patterned depth map.

![2017-09-30 17_18_08-image 2](https://user-images.githubusercontent.com/13685803/31049558-84c7a328-a603-11e7-953f-9d3051a48e58.png)

DepthPerspective works better than DepthPlanner, but got more or less the same problem as mentioned above.  You can see this in the screenshot below, where the gray rectangle in the upper-right corner shows what I got from DepthPerspective (converted froma 2D array of floats to RGB-gray).  There most of its left side is showing incorrect depth. 

![2017-09-30 17_15_28-airsimnh 64-bit pcd3d_sm5](https://user-images.githubusercontent.com/13685803/31049634-0f063eae-a605-11e7-977a-ba8559b4363b.png)

As a reference, the depth map at the upper-right corner below shows what I got from a *normal* DepthPerspective map.

![2017-09-30 17_27_35-airsimnh 64-bit pcd3d_sm5](https://user-images.githubusercontent.com/13685803/31049633-01a91376-a605-11e7-98c1-5495be9a0223.png)

**Comment by sytelus** [comment]
I have been looking at this issue. It seems that the problem is in this specific environment and its triggering some bug in Unreal. In Blocks environment things are working all fine. I'm wondering if there is any issue with sky light or some rendering settings in this environment. If you are willing to mess with Unreal, you are welcome to debug this as well :)

**Comment by Mayankm96** [comment]
Hm well I am facing a bit of an issue with depth map too right now. I changed the PIP camera by 90 degrees so that they face towards the ground now instead of front, and the depth map doesn't seem correct. Any suggestions on this?

![depth_am](https://user-images.githubusercontent.com/12863862/31053297-2fec6a86-a6b8-11e7-81a3-7c2c80441fa9.JPG)

**Comment by Kjell-K** [comment]
@sytelus For Blocks and Neighbourhood the issue is remaining with the new master.

![unbenannt](https://user-images.githubusercontent.com/29546195/31056453-1864d8ac-a6d2-11e7-8e09-ab1127f2ae79.PNG)

**Comment by sytelus** [comment]
Ah! Finally found the cause and have fixed it. Please try out the latest code. I'll update the binaries soon.

**Comment by Kjell-K** [comment]
@sytelus Yes the 180° is solved! But on the other side the issue #491 as black/white over all the 360°. I will post there.

**Comment by sytelus** [comment]
Binaries are updated. We also have new Downtown environment.

**Comment by kaihuchen** [comment]
@sytelus    I am still seeing binaries posted from 6 days ago here [here](https://github.com/Microsoft/AirSim/releases/tag/v1.1.1). Am I looking at the wrong place?
